API Fixed
valdazo/ubp-lab4-practicos pull request #11
Opened 2019-08-19 17:12 UTC by gonzagrisa

Fixed were made and now code and documentation look a lot better

2019-08-20 15:02 UTC, gonzagrisa commented
ps: don't look at app.js

2019-08-23 22:02 UTC, valdazo requested changes

2019-08-23 22:02 UTC, valdazo commented on grisafi/handler/apphandler.js
> +                    data: {
just to keep an uniform result, add the code as part of the returned json.

2019-08-23 22:02 UTC, valdazo commented on grisafi/handler/apphandler.js
> +                    code: 404,
change this code to make it the same than the response status.

2019-08-23 22:02 UTC, valdazo commented on grisafi/handler/apphandler.js
> +        res.status(200).json({ data: books });
decide weather or not you want to put the code as part of the result json. If you want to do it, add it to all the responses.

2019-08-23 22:02 UTC, valdazo commented on grisafi/handler/apphandler.js
> +let f = require('../lib/auxFuncs');
Use a meaningful name instead of f

2019-08-23 22:02 UTC, valdazo commented on grisafi/handler/apphandler.js
> +let v = require('../lib/validators');
Use a meaningful name instead of v

2019-08-23 22:02 UTC, valdazo commented on grisafi/app.js
>  const DIA_EN_MILISEGUNDOS = 1000 * 60 * 60 * 24;
This is defined twice, one definition is here, the other definition is in apphandler.js

2019-08-23 22:02 UTC, valdazo commented on grisafi/lib/auxFuncs.js
> +        let prest = new Array();
english

2019-08-23 22:02 UTC, valdazo commented on grisafi/lib/validators.js
> +        if(/^\d*$/.test(quantity) && /^\d*$/.test(id) && typeof(title)=='string'){
Shouldn't be /^\d+$/ instead

2019-08-23 22:02 UTC, valdazo commented on grisafi/lib/validators.js
> +        if(/^\d*$/.test(quantity) && /^\d*$/.test(id) && typeof(title)=='string'){
Is an empty string valid aswell?

2019-08-23 22:02 UTC, valdazo commented on grisafi/handler/apphandler.js
> +                    success: true,
use one of the many options added.
Either use
code : 200, or success: true, or status:success

2019-08-23 22:02 UTC, valdazo commented on grisafi/handler/apphandler.js
> +            res.status(200).json({
status should be 204

2019-08-25 22:05 UTC, gonzagrisa commented on grisafi/lib/auxFuncs.js
> +        let prest = new Array();
my bad

2019-08-30 18:57 UTC, valdazo approved these changes

2019-08-30 18:57 UTC, merged