Rest API para manejo de biblioteca
valdazo/ubp-lab4-practicos pull request #7
Opened 2019-05-20 23:34 UTC by soficantarelli

2019-05-21 00:19 UTC, TinoCle commented on cantarelli/app.js
> +        res.status(400);
You should use 404 as status code when the request wasn't found

2019-05-21 00:19 UTC, TinoCle commented on cantarelli/app.js
> +var server = app.listen(8080, '127.0.0.1', function() {
The host is set to '127.0.0.1' or 'localhost' by default, you can avoid that paramether

2019-05-21 00:19 UTC, TinoCle commented on cantarelli/app.js
> +    console.log("app corriendo en: http://%s:%s", host, port)
```console.log(`app corriendo en ${server.address().address}:${server.address().port}`)```
Is valid too.

2019-05-21 00:19 UTC, TinoCle commented on cantarelli/app.js
> +        res.status(400).send("No se puede eliminar el libro");
Tell the user that the book wasn't found

2019-05-25 16:55 UTC, gonzagrisa commented on cantarelli/app.js
> +                return libros[i].cantidad - libros[i].disponibles();
la funcion disponibles ya hace cantidad - disponibles
```
this.disponibles = function() {
        var contador = 0;
        for(const prest of prestamos) {
            if(prest.idLibro ==  this.id){
                contador++;
            }
        }
        return this.cantidad - contador;
```

2019-05-25 17:01 UTC, gonzalogrisafi reviewed
cambios menores

2019-05-27 03:09 UTC, emicalvacho approved these changes

2019-05-27 13:45 UTC, valdazo requested changes

2019-05-27 13:45 UTC, valdazo commented on cantarelli/app.js
> +libros.push(new Libro(1, "Libro 1", 1));
Agreagar algo como
`TODO: datos puestos para agregar elementos de prueba, a borrar cuando agregue la base de datos`

2019-05-27 13:45 UTC, valdazo commented on cantarelli/app.js
> +    let aux = -1;
En este método, el resultado debería ser booleano, de esa forma las llamadas que lo usan son mucho mas claras
```
    let existe = false;
    for (let i = 0; i < coleccion.length; i++) {
        if(idAux == coleccion[i].id){
            existe = true;
        }      
    }
    return existe;
```

Y luego, en el uso, por ejemplo en un if, seria
```
if (buscarPorId(idLibro, libros)){
....
}
```

2019-05-27 13:45 UTC, valdazo commented on cantarelli/app.js
> +function librosAdeudados(idSocio){
El método podria devolver un booleano, true si el libro se adueda, falso en el caso opuesto.

2019-05-27 13:45 UTC, valdazo commented on cantarelli/app.js
> +/* Un socio puede devolver un libro prestado*/
Por las condiciones que pusimos un socio puede obtener varas veces un prestamo de un libro, por lo que lo mas conveniente seria quizas hacer un delete sobre prestamo, con el id del prestamo. De todas formas esto esta bien, en el futuro si vemos que necesitamos cambiarlo lo hacemos

2019-05-27 21:22 UTC, gonzalogrisafi approved these changes
todo muy lindo

2019-05-27 21:55 UTC, valdazo approved these changes

2019-05-27 21:56 UTC, merged